print("--------- Formatting String --------")

print("3: {}".format('Aven'))
print("4: {:8}".format('Aven'))
print("5: {:<8}".format('Aven'))
print("6: {:>8}".format('Aven'))
print("7: {:#<8}".format('Aven'))
print("8: {:#>8}".format('Aven'))
print("9: {:#^8}".format('Aven'))

print()

print('-------- Truncating String ------------')
print("14: {}".format('Aven'))
print("15: {:8s}".format('Aven'))
print("16: {:<8.2s}".format('Aven'))
print("17: {:>8.2}".format('Aven'))
print("18: {:*<8.2}".format('Aven'))
print("19: {:*>8.2}".format('Aven'))
print("20: {:*^8.2}".format('Aven'))
